# Generated by Django 5.2.4 on 2025-07-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camping_Tent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('Features', models.CharField(max_length=100)),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Address', models.CharField(max_length=500)),
                ('Days', models.IntegerField()),
                ('Night', models.IntegerField()),
                ('Fake_Price', models.IntegerField()),
                ('Real_Price', models.IntegerField()),
                ('Overviwe', models.TextField()),
                ('Embed_code', models.TextField(blank=True, null=True)),
                ('Main_Image', models.ImageField(blank=True, null=True, upload_to='camping/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampingExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=500)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='Camping.camping_tent')),
            ],
        ),
        migrations.CreateModel(
            name='CampingHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=500)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='Camping.camping_tent')),
            ],
        ),
        migrations.CreateModel(
            name='CampingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='camping/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='camping/images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='camping/images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='camping/images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='camping/images/')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Camping.camping_tent')),
            ],
        ),
        migrations.CreateModel(
            name='CampingInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=500)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='Camping.camping_tent')),
            ],
        ),
    ]
