# Generated by Django 5.2.4 on 2025-08-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camping_tent',
            name='Pickup_Airport_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camping_tent',
            name='Pickup_Home_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camping_tent',
            name='Pickup_Hotel_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camping_tent',
            name='Pickup_Railway_Station_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camping_tent',
            name='Single_Camp_People',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
