# Generated by Django 5.2.4 on 2025-08-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0002_camping_tent_pickup_airport_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('quantity', models.IntegerField(default=1)),
                ('pickup_service', models.CharField(blank=True, choices=[('home', 'Pickup From Home'), ('hotel', 'Pickup From Hotel'), ('railway', 'Pickup From Railway Station'), ('airport', 'Pickup From Airport')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('admin_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('camp_location_url', models.URLField(blank=True, null=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Camping.camping_tent')),
            ],
        ),
    ]
