# Generated by Django 5.2.4 on 2025-08-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
