# Generated by Django 5.2.4 on 2025-08-04 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0004_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('tent_quantity', models.PositiveIntegerField(default=1)),
                ('pickup_home', models.BooleanField(default=False)),
                ('pickup_hotel', models.BooleanField(default=False)),
                ('pickup_railway', models.BooleanField(default=False)),
                ('pickup_airport', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('location_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Camping.camping_tent')),
            ],
        ),
    ]
