# Generated by Django 5.2.4 on 2025-08-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0005_campbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='campbooking',
            name='tent_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
