# Generated by Django 5.2.4 on 2025-08-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0006_campbooking_tent_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampBooking',
        ),
    ]
