# Generated by Django 5.2.4 on 2025-08-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0008_campbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampBooking',
        ),
    ]
