# Generated by Django 5.2.4 on 2025-08-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0012_campbooking_delete_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampBooking',
        ),
    ]
