# Generated by Django 5.2.4 on 2025-08-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0014_campbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampBooking',
        ),
    ]
