# Generated by Django 5.2.4 on 2025-08-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0016_campbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='campbooking',
            name='confirmation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='booking_pdfs/'),
        ),
    ]
