# Generated by Django 5.2.4 on 2025-08-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0017_campbooking_confirmation_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='campbooking',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
