# Generated by Django 5.2.4 on 2025-08-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0018_campbooking_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campbooking',
            name='email_sent',
        ),
    ]
