# Generated by Django 5.2.4 on 2025-07-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='destinations/')),
                ('description', models.TextField()),
                ('distance_from_jaisalmer', models.DecimalField(decimal_places=2, help_text='Distance from Jaisalmer in km', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['distance_from_jaisalmer'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_heading', models.CharField(help_text='छोटी heading', max_length=200)),
                ('highlight_text', models.CharField(help_text='heading में span वाला text', max_length=100)),
                ('description', models.TextField(help_text='Paragraph text')),
                ('heading_image', models.ImageField(help_text='PNG image for heading', upload_to='home/')),
            ],
        ),
        migrations.CreateModel(
            name='TopPalace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='palaces/')),
            ],
            options={
                'verbose_name': 'Top Palace',
                'verbose_name_plural': 'Top Palaces',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('short_content', models.TextField()),
                ('couple_image', models.ImageField(help_text='Upload Couple Image', upload_to='whychoose/')),
                ('tree_image1', models.ImageField(help_text='Upload First Tree Image', upload_to='whychoose/')),
                ('tree_image2', models.ImageField(help_text='Upload Second Tree Image', upload_to='whychoose/')),
            ],
            options={
                'verbose_name': 'Why Choose Us Section',
                'verbose_name_plural': 'Why Choose Us Sections',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
