# Generated by Django 5.2.4 on 2025-08-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('branches_count', models.CharField(default='20+', max_length=50)),
                ('branches_text', models.CharField(default='Global Branches', max_length=100)),
                ('destinations_count', models.CharField(default='15+', max_length=50)),
                ('destinations_text', models.CharField(default='Destinations Covered', max_length=100)),
                ('customers_count', models.CharField(default='50K+', max_length=50)),
                ('customers_text', models.CharField(default='Happy Customers', max_length=100)),
                ('button_text', models.CharField(default='Discover Us', max_length=50)),
                ('button_link', models.URLField(default='#')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
