# Generated by Django 5.2.4 on 2025-08-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='heading',
        ),
    ]
