# Generated by Django 5.2.4 on 2025-08-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aboutsection_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='button_text',
        ),
    ]
