# Generated by Django 5.2.4 on 2025-08-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
