# Generated by Django 5.2.4 on 2025-08-31 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='message',
            field=models.TextField(default=datetime.datetime(2025, 8, 31, 7, 55, 50, 523164, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
