# Generated by Django 5.2.4 on 2025-07-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_Main_img', models.ImageField(blank=True, null=True, upload_to='Hotel_img/')),
                ('Hotel_Name', models.CharField(max_length=255)),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Stars', models.CharField(max_length=100)),
                ('Hotel_Address', models.CharField(max_length=500)),
                ('Fake_Price', models.IntegerField()),
                ('Real_Price', models.IntegerField()),
                ('Airport_pickup_price', models.IntegerField(default=0)),
                ('Railway_pickup_price', models.IntegerField(default=0)),
                ('Hotel_Overview', models.TextField()),
                ('Hotel_L_Map_Embed_Code', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='Hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Hotel_imgs/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Hotel_imgs/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Hotel_imgs/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='Hotel_imgs/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='Hotel_imgs/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Hotel.hotel')),
            ],
        ),
    ]
