# Generated by Django 5.2.4 on 2025-08-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
