# Generated by Django 5.2.4 on 2025-08-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_booking_admin_contact_number_booking_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='booking_pdfs/'),
        ),
    ]
