# Generated by Django 5.2.4 on 2025-08-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_booking_confirmation_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='confirmation_pdf',
        ),
    ]
