# Generated by Django 5.2.4 on 2025-07-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Activity/')),
                ('Features', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Name', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('location', models.CharField(max_length=500)),
                ('Real_price', models.IntegerField()),
                ('Fake_price', models.IntegerField()),
                ('Time_Duration', models.CharField(max_length=50)),
                ('Group_size', models.IntegerField()),
                ('Overviwe', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=500)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='Adventure.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=500)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='Adventure.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Activity/multiple_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Activity/multiple_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Activity/multiple_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='Activity/multiple_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='Activity/multiple_images/')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Adventure.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=500)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='Adventure.activity')),
            ],
        ),
    ]
