# Generated by Django 5.2.4 on 2025-08-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Pickup_Airport_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='Pickup_Home_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='Pickup_Hotel_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='Pickup_Railway_Station_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
